### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TheAlexLichter** [D2Arsenal/d2arsenal.com#4]
## Intro

This issue should serve as a rough roadmap for the future. Please feel free to pick up issues as you like as this is a community effort 🙏 

## Perks

* [ ] #10

## Masterworks
* [ ] Add Exotic Catalyst with toggles

## Search
* [ ] #5
* [ ] #6
* [ ] #7
* [ ] #8
* [ ] #9

## Extras
* [ ] DIM Wishlist
* [ ] Hide retired perks
* [ ] Damage Falloff
* [ ] TTK
* [ ] Reload speed stat

## Misc
  * [ ] Improve site structure by providing a list of weapons, e.g. by type
  * [ ] Incorporate https://github.com/DestinyItemManager/d2-additional-info
  * [ ] (HUGE) - Stat usage á la light.gg
 
## Performance
  * [ ] Use image proxy for icons and screenshots, e.g. via cloudflare 👀
  * [ ] Give weapon icons explicit height

## Research (TODO)
  * [ ] Stat changes via "Perks on/off" button for e.g. surplus
  * [ ] Stats: Elemental capacitor from subclasses
